# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66715fff546b9de0dab6ed7b0434aec37f2a17a20a4accb27195f4776351a1788179a9d2ebeb990af0683af212c1c0ef74e4c9fb9e683bda07b329f6e0ea0994

test:
  secret_key_base: 86e18865b74d0db72548c8b031b237eb3b750877a9462cd7d641cb39c43e0e4ad4dd0c8a8090333a7060a94c7b5f74d1c6192de6ffcbfc6da1a946636db15833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
